name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hinorpio/comp7940_bot:latest
           
      - name: Deploy to AWS Lightsail Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            docker pull hinorpio/comp7940_bot:latest
            docker stop tg-bot || true
            docker rm tg-bot || true
            docker run -d --name tg-bot -p 80:5000 hinorpio/comp7940_bot:latest
